# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OCNRMfeIaPypao8Jw_jZeGiEMdiNIfvh
"""

import pandas as pd 

gender = pd.read_csv('gender_classification_v7.csv')
gender.head()

gender.isnull().any()

gender.info()

X = gender.iloc[:,:-1].values
y = gender.iloc[:,-1].values

print(X)

print(y)

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.1, random_state=123)

from sklearn.tree import DecisionTreeClassifier

tree_model = DecisionTreeClassifier()

tree_model = tree_model.fit(X_train, y_train)

# evaluasi
from sklearn.metrics import accuracy_score

y_pred = tree_model.predict(X_test)

acc_secore = round(accuracy_score(y_pred, y_test),3)

print('Accuracy:', acc_secore)

print(tree_model.predict([[1,	13.5,	5.9,	0,	0,	0,	0	]]))